<?php

/**
 * @file
 * Example CKEditor Widget implementations for Drupal 7.
 *
 * This example module accompanies a presentation made at 2014 Twin Cities
 * Drupal Camp, entitled "Help Your WYSIWYG Help You: Creating Custom CKEditor
 * Widgets".
 *
 * Session URL: http://2014.tcdrupal.org/session/help-your-wysiwyg-help-you-creating-custom-ckeditor-widgets
 * Slides URL: http://ten7.com/ckeditor_widgets
 * 
 * Accordion widget added by Banoodle.
 */

/**
 * Implements hook_ckeditor_plugin().
 */
function banoodle_widgets_ckeditor_plugin() {
  return array(
    'callout' => array(
      'name' => 'callout',
      'desc' => t('CKEditor widget for a callout box.'),
      // The path to the CKEditor plugins directory, with the trailing slash.
      // Directory must contain a "plugin.js" file.
      'path' => drupal_get_path('module', 'banoodle_widgets') . '/plugins/callout/',
      // Register the toolbar icon to be used in the Drupal admin interface.
      'buttons' => array(
        'callout' => array(
          'label' => 'Callout',
          'icon' => 'icon-callout.png',
        ),
      ),
    ),
    'accordion' => array(
      'name' => 'accordion',
      'desc' => t('CKEditor widget for an accordion.'),
      'path' => drupal_get_path('module', 'banoodle_widgets') . '/plugins/accordion/',
      'buttons' => array(
        'accordion' => array(
          'label' => 'Accordion',
          'icon' => 'icon-accordion.png',
        ),
      ),
    ),
  );
}

/**
 * Implements hook_entity_view().
 */
function banoodle_widgets_entity_view($entity, $type, $view_mode, $langcode) {
  // Make the jQuery UI Accordion plugin available.
  drupal_add_library('system', 'ui.accordion');
  // Load our JS file that implements jQuery UI Accordion.
  drupal_add_js(drupal_get_path('module', 'banoodle_widgets') . '/js/banoodle_widgets.js');
  // Load custom CSS for styling callout widgets.
  drupal_add_css(drupal_get_path('module', 'banoodle_widgets') . '/css/banoodle_widgets.css');
}
